export const users = [
  {
    _id: '66979fb031a1bb408c314fcd',
    index: 0,
    guid: '2102a451-a402-432a-9f2f-2ef07e311cf1',
    isActive: false,
    balance: '$2,372.19',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'blue',
    name: 'Ethel Payne',
    gender: 'female',
    company: 'SQUISH',
    email: 'ethelpayne@squish.com',
    phone: '+1 (862) 534-2691',
    address: '644 Falmouth Street, Tibbie, Arizona, 2838',
    about:
      'Dolore est quis aute pariatur nisi minim non cupidatat Lorem eu. Officia ex ipsum non laboris reprehenderit velit ullamco qui id magna sit in in mollit. Sit esse nostrud laborum cillum ullamco consectetur ea reprehenderit id nisi laboris qui labore elit. Laboris amet elit ea laboris eu est. Lorem cupidatat reprehenderit sunt labore ex laborum ipsum culpa nulla mollit occaecat esse ipsum.\r\n',
    registered: '2019-08-13T11:00:48 -03:00',
    latitude: 46.109936,
    longitude: 11.209007,
    tags: [
      'sunt',
      'labore',
      'culpa',
      'pariatur',
      'incididunt',
      'reprehenderit',
      'amet',
    ],
    friends: [
      {
        id: 0,
        name: 'Hunter Frank',
      },
      {
        id: 1,
        name: 'Mayer Walls',
      },
      {
        id: 2,
        name: 'Lottie Henry',
      },
    ],
    greeting: 'Hello, Ethel Payne! You have 8 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66979fb01adda00f429047f4',
    index: 1,
    guid: '8538525f-0495-4137-960e-a7a6a2da3b1a',
    isActive: false,
    balance: '$3,692.20',
    picture: 'http://placehold.it/32x32',
    age: 29,
    eyeColor: 'blue',
    name: 'Deena Burke',
    gender: 'female',
    company: 'PANZENT',
    email: 'deenaburke@panzent.com',
    phone: '+1 (926) 431-3105',
    address: '465 Madison Place, Alamo, New Jersey, 4286',
    about:
      'Lorem et nostrud et id qui sint proident. Aliquip duis esse aute exercitation laboris eu sint sunt et quis quis. Irure tempor culpa tempor commodo aliqua fugiat occaecat cillum tempor minim pariatur. Veniam consequat nulla commodo reprehenderit id ad ut cupidatat. Culpa minim ipsum laborum ex ad tempor ullamco proident duis proident nostrud minim ipsum. Aliquip occaecat occaecat nostrud irure duis sit incididunt sit do. Est amet nisi anim nisi.\r\n',
    registered: '2017-04-17T04:08:49 -03:00',
    latitude: 15.469532,
    longitude: -9.452207,
    tags: ['ea', 'quis', 'Lorem', 'sint', 'labore', 'ex', 'aliquip'],
    friends: [
      {
        id: 0,
        name: 'Maritza Petty',
      },
      {
        id: 1,
        name: 'Marlene Hinton',
      },
      {
        id: 2,
        name: 'Cathleen Marshall',
      },
    ],
    greeting: 'Hello, Deena Burke! You have 7 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66979fb0c5ef0f393c9222ae',
    index: 2,
    guid: '853fe08d-c0e1-41dd-8d81-8e7eab111ac4',
    isActive: true,
    balance: '$3,310.01',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'green',
    name: 'Roberson Salinas',
    gender: 'male',
    company: 'FIBRODYNE',
    email: 'robersonsalinas@fibrodyne.com',
    phone: '+1 (933) 405-3284',
    address: '999 Monument Walk, Churchill, Rhode Island, 5847',
    about:
      'Veniam incididunt eiusmod eu esse aliqua eu eu tempor Lorem ullamco. Enim officia id eiusmod labore proident consequat proident nisi laborum excepteur. Ad ea laboris exercitation ipsum dolore laborum incididunt eiusmod est aliqua minim proident nisi. Fugiat labore incididunt deserunt pariatur in tempor esse enim pariatur irure duis ad pariatur commodo. Sint voluptate exercitation est veniam. Consequat laboris excepteur veniam amet incididunt occaecat enim in amet excepteur. Magna qui sit incididunt laborum voluptate cillum esse veniam ut ipsum sint quis.\r\n',
    registered: '2024-05-20T06:19:44 -03:00',
    latitude: 4.974396,
    longitude: -92.118677,
    tags: [
      'eiusmod',
      'pariatur',
      'ut',
      'adipisicing',
      'proident',
      'consectetur',
      'tempor',
    ],
    friends: [
      {
        id: 0,
        name: 'Dollie Mcclain',
      },
      {
        id: 1,
        name: 'Benson Brock',
      },
      {
        id: 2,
        name: 'Debra Dawson',
      },
    ],
    greeting: 'Hello, Roberson Salinas! You have 8 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66979fb0d921c5af3b9bc4c9',
    index: 3,
    guid: 'b730ef91-0bff-43ed-823b-5d6850ca22b7',
    isActive: false,
    balance: '$2,253.38',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'green',
    name: 'Teri Mitchell',
    gender: 'female',
    company: 'COMBOGEN',
    email: 'terimitchell@combogen.com',
    phone: '+1 (818) 454-2681',
    address: '901 Vine Street, Wedgewood, Alabama, 4224',
    about:
      'Fugiat sunt esse dolor ea nostrud ea proident mollit reprehenderit aliquip officia. Labore sit quis sunt cupidatat. Ea laborum ex mollit incididunt.\r\n',
    registered: '2024-03-15T04:31:11 -03:00',
    latitude: -20.252501,
    longitude: -97.579465,
    tags: ['cillum', 'id', 'ad', 'labore', 'in', 'eiusmod', 'commodo'],
    friends: [
      {
        id: 0,
        name: 'Hays Preston',
      },
      {
        id: 1,
        name: 'Joni Jackson',
      },
      {
        id: 2,
        name: 'Montoya Bell',
      },
    ],
    greeting: 'Hello, Teri Mitchell! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66979fb0dc72a680ad6f37a6',
    index: 4,
    guid: 'df3066d9-48a7-44ac-bff8-a4a5343a855d',
    isActive: true,
    balance: '$2,686.63',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'blue',
    name: 'Salazar Morton',
    gender: 'male',
    company: 'XPLOR',
    email: 'salazarmorton@xplor.com',
    phone: '+1 (834) 572-2390',
    address: '151 Agate Court, Lopezo, Maryland, 3311',
    about:
      'Irure qui dolore commodo culpa consectetur tempor reprehenderit quis id eu officia deserunt. Culpa nisi sit sunt voluptate quis sunt in proident. Nostrud tempor adipisicing anim ea duis sunt cupidatat officia eu voluptate aliquip cillum ex dolore. Reprehenderit proident aliquip excepteur sit nostrud sit laborum culpa pariatur aliqua deserunt quis dolor reprehenderit. Fugiat aute excepteur enim nulla reprehenderit commodo laborum non ad. Reprehenderit dolore minim sunt reprehenderit quis ipsum consectetur sit ullamco non Lorem adipisicing reprehenderit.\r\n',
    registered: '2022-04-05T05:28:51 -03:00',
    latitude: 1.831682,
    longitude: 17.104029,
    tags: ['ipsum', 'id', 'duis', 'incididunt', 'quis', 'elit', 'do'],
    friends: [
      {
        id: 0,
        name: 'Lana Schwartz',
      },
      {
        id: 1,
        name: 'Burgess Grant',
      },
      {
        id: 2,
        name: 'Lori Goodman',
      },
    ],
    greeting: 'Hello, Salazar Morton! You have 4 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66979fb0809c89383c66eaaa',
    index: 5,
    guid: '50b88efa-1a16-4271-936d-dc06a7dd7bdf',
    isActive: false,
    balance: '$3,822.72',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'blue',
    name: 'Wilkerson Molina',
    gender: 'male',
    company: 'SIGNITY',
    email: 'wilkersonmolina@signity.com',
    phone: '+1 (940) 459-2423',
    address: '696 Forest Place, Gordon, Illinois, 473',
    about:
      'Enim anim labore labore dolor. Sit voluptate voluptate consectetur in enim sint sit aliquip aliqua duis. Velit dolor commodo voluptate et esse magna esse. Nulla et commodo irure ullamco sint voluptate. Exercitation sunt ipsum cupidatat magna fugiat Lorem consequat culpa consectetur ullamco velit minim. Qui do anim Lorem aute enim elit voluptate reprehenderit enim. Commodo do veniam laborum consectetur.\r\n',
    registered: '2021-10-17T08:18:52 -03:00',
    latitude: 87.116185,
    longitude: -37.94497,
    tags: ['ut', 'in', 'ad', 'dolore', 'aliqua', 'minim', 'occaecat'],
    friends: [
      {
        id: 0,
        name: 'Barron Kelly',
      },
      {
        id: 1,
        name: 'Justine York',
      },
      {
        id: 2,
        name: 'Maxwell Franks',
      },
    ],
    greeting: 'Hello, Wilkerson Molina! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66979fb03936ed8a7fecb2b9',
    index: 6,
    guid: '30d2ef1b-9cb7-40e2-93db-8297f31a0655',
    isActive: true,
    balance: '$2,277.30',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'brown',
    name: 'Jensen Kennedy',
    gender: 'male',
    company: 'CEMENTION',
    email: 'jensenkennedy@cemention.com',
    phone: '+1 (879) 476-3585',
    address: '253 Kenilworth Place, Nile, Northern Mariana Islands, 3928',
    about:
      'Eu qui proident do in sit cupidatat exercitation aliqua Lorem id non adipisicing est reprehenderit. Id ad nostrud excepteur quis consequat ipsum eu ea mollit non est. In deserunt officia nisi aliqua nulla reprehenderit.\r\n',
    registered: '2015-12-10T01:13:22 -03:00',
    latitude: 77.953944,
    longitude: 45.680653,
    tags: ['sit', 'mollit', 'ad', 'aliquip', 'aliqua', 'cillum', 'id'],
    friends: [
      {
        id: 0,
        name: 'Ortega Hooper',
      },
      {
        id: 1,
        name: 'Arline Albert',
      },
      {
        id: 2,
        name: 'Levy Tran',
      },
    ],
    greeting: 'Hello, Jensen Kennedy! You have 1 unread messages.',
    favoriteFruit: 'banana',
  },
];
